#ifndef UI_ACTION_HPP
#define UI_ACTION_HPP

enum class UiAction {
    NONE=0,
    STARTUP_EXIT,
    STARTUP_PLAY_SCENARIO=32,
    STARTUP_ZOO_ITEMS=35,
    STARTUP_PLAY_FREEFORM=39,
    STARTUP_CREDITS=40
};

#endif // UI_ACTION_HPP